In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.linear_model

In [2]:
dados = pd.read_csv('dados/houses_train.csv')

In [3]:
dados

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [4]:
dados_casa = dados

In [ ]:
#Encontrar a correlação :
sns.pairplot(dados_casa)

In [ ]:
dados_casa.corr()

In [ ]:
#Regressão aplicada 
sns.pairplot(dados_casa, x_vars = ['LotArea'], y_vars = ['SalePrice'], height = 5, kind = 'reg')
sns.pairplot(dados_casa, x_vars = ['LotFrontage'], y_vars = ['SalePrice'], height = 5, kind= 'reg')
sns.pairplot(dados_casa, x_vars = ['MSSubClass'], y_vars = ['SalePrice'], height = 5, kind= 'reg')
sns.pairplot(dados_casa, x_vars = ['MoSold'], y_vars = ['SalePrice'], height = 5, kind= 'reg')

In [72]:
#Correlação
data_corr = dados_casa.corr().SalePrice.sort_values(ascending=False)[:10].index
data_corr


Index(['SalePrice', 'OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea',
       'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt'],
      dtype='object')

In [73]:
x = dados[data_corr].drop(['SalePrice'],axis = 1)
y = dados.SalePrice

In [74]:
x.isna()

OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  \
0           False      False       False       False        False     False   
1           False      False       False       False        False     False   
2           False      False       False       False        False     False   
3           False      False       False       False        False     False   
4           False      False       False       False        False     False   
...           ...        ...         ...         ...          ...       ...   
1455        False      False       False       False        False     False   
1456        False      False       False       False        False     False   
1457        False      False       False       False        False     False   
1458        False      False       False       False        False     False   
1459        False      False       False       False        False     False   

      FullBath  TotRmsAbvGrd  YearBuilt  
0        False         False      False  
1        False         False      False  
2        False         False      False  
3        False         False      False  
4        False         False      False  
...        ...           ...        ...  
1455     False         False      False  
1456     False         False      False  
1457     False         False      False  
1458     False         False      False  
1459     False         False      False  

[1460 rows x 9 columns]

In [75]:
#Pega dentro do dataset de forma aleatória até completar a % dos dados de teste e de treino
from sklearn.model_selection import train_test_split

In [76]:
#Apresentar os dados de treino - .fit 
#Quero gerar uma predição em cima do teste
#25% dos meus dados vou usar pra teste
#75% dos dados vai pro meu treino

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 43)


In [77]:
from sklearn.linear_model import LinearRegression

In [78]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x,y)
lr.coef_, lr.intercept_

(array([ 2.09227655e+04,  5.13679300e+01,  1.06342357e+04,  1.45088448e+01,
         1.92465885e+01,  1.39481175e+01, -5.41031135e+03, -8.66391119e+01,
         3.45362905e+02]),
 -758532.9134995528)

In [21]:
x_train.head()

OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  \
242            5       1440           1         352          540       889   
617            6        832           2         528          832       832   
539            8       1601           2         670         1581      1601   
264            5        764           2         504          680       764   
392            5        882           1         294            0       882   

     FullBath  TotRmsAbvGrd  YearBuilt  
242         1             6       1900  
617         1             4       1954  
539         2             6       2001  
264         1             4       1925  
392         1             5       1959

In [20]:
lr.coef_

array([ 2.09227655e+04,  5.13679300e+01,  1.06342357e+04,  1.45088448e+01,
        1.92465885e+01,  1.39481175e+01, -5.41031135e+03, -8.66391119e+01,
        3.45362905e+02])

In [25]:
lr.intercept_

-758532.9134995528

In [27]:
y_pred = lr.predict(x_test)
y_pred

array([161608.09892031, 178173.0660633 , 179161.11988909, 185408.5935939 ,
       189859.12933911, 252632.43340416,  65555.19459859, 175311.53669924,
       118054.38661065, 217684.81108925, 155511.14944097, 303354.57090068,
       134596.73926691,  93224.59461102, 205842.57101853, 131316.12183543,
       141755.92016814,  -1978.07334251, 132063.01930535, 152080.01297846,
       308825.51570784, 102671.22837459, 240031.12521459, 258213.13713839,
       257595.61888922, 359003.43438198,  92124.85524953, 149706.61506448,
       111849.92010545, 127782.46330615, 154111.55480126,  92191.20096806,
       126779.19245885, 128287.51272601,  85343.68531117, 195441.81844375,
       349046.82603478, 226738.835817  , 252829.79184522, 152512.01499574,
       316217.53857102, 185853.202591  ,   3512.27199984, 136303.06249625,
       209527.38105147, 113707.63274053, 147065.83477222, 237207.70515797,
       172805.47081147, 248807.13863667,  96824.7647761 , 160764.09970915,
       187110.03946484, 3

In [28]:
x_test.head()

OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  \
860             7       1426           1         216          912       912   
1146            6       1298           2         403         1298      1298   
1092            6       1694           2         576         1181      1390   
1018            7       1472           2         402          384       802   
628             5       2080           2         504         1040      1040   

      FullBath  TotRmsAbvGrd  YearBuilt  
860          1             7       1918  
1146         2             5       1985  
1092         2             7       1925  
1018         2             7       1991  
628          1             9       1969

In [29]:

from sklearn.metrics import mean_squared_error

In [30]:
#Preço da casa está variando entre + 37757 e - 37757
#Aqui o cliente pode dizer se essa variação está boa ou não para a venda da casa 
np.sqrt(mean_squared_error(y_test,y_pred))

37757.830507969935

Pré-Processamento dos dados

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder

In [32]:
x

OverallQual  GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  \
0               7       1710           2         548          856       856   
1               6       1262           2         460         1262      1262   
2               7       1786           2         608          920       920   
3               7       1717           3         642          756       961   
4               8       2198           3         836         1145      1145   
...           ...        ...         ...         ...          ...       ...   
1455            6       1647           2         460          953       953   
1456            6       2073           2         500         1542      2073   
1457            7       2340           1         252         1152      1188   
1458            5       1078           1         240         1078      1078   
1459            5       1256           1         276         1256      1256   

      FullBath  TotRmsAbvGrd  YearBuilt  
0            2             8       2003  
1            2             6       1976  
2            2             6       2001  
3            1             7       1915  
4            2             9       2000  
...        ...           ...        ...  
1455         2             7       1999  
1456         2             7       1978  
1457         2             9       1941  
1458         1             5       1950  
1459         1             6       1965  

[1460 rows x 9 columns]

In [34]:
min_max = MinMaxScaler()
scaled_x = min_max.fit_transform(x.drop(['OverallQual'], axis = 1))
scaled_x[0]

array([0.25923135, 0.5       , 0.3864598 , 0.1400982 , 0.11977972,
       0.66666667, 0.5       , 0.94927536])

In [43]:
#É um transformador da variável que for colocada nele.
#Tem fi e fit_transformer
one = OneHotEncoder(categories = 'auto')
qual_trans = one.fit_transform(x[['OverallQual']])
qual_trans.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [46]:
#Categoria 7 nota 1
one.categories_

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)]

In [45]:
#Cada nota tem um peso especifico 
#Codificado
qual_trans[0].todense()

matrix([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [48]:
qual_trans = pd.DataFrame(qual_trans.todense(),columns=one.categories_)
qual_trans.columns = ['qual_'+str(x) for x in list(zip(*qual_trans.columns.values))[0]]

In [50]:
df_scaled = pd.DataFrame(scaled_x,columns=x.drop(['OverallQual'],axis=1).columns)
df_scaled


GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  FullBath  \
0      0.259231        0.50    0.386460     0.140098  0.119780  0.666667   
1      0.174830        0.50    0.324401     0.206547  0.212942  0.666667   
2      0.273549        0.50    0.428773     0.150573  0.134465  0.666667   
3      0.260550        0.75    0.452750     0.123732  0.143873  0.333333   
4      0.351168        0.75    0.589563     0.187398  0.186095  0.666667   
...         ...         ...         ...          ...       ...       ...   
1455   0.247362        0.50    0.324401     0.155974  0.142038  0.666667   
1456   0.327619        0.50    0.352609     0.252373  0.399036  0.666667   
1457   0.377920        0.25    0.177715     0.188543  0.195961  0.666667   
1458   0.140166        0.25    0.169252     0.176432  0.170721  0.333333   
1459   0.173700        0.25    0.194640     0.205565  0.211565  0.333333   

      TotRmsAbvGrd  YearBuilt  
0         0.500000   0.949275  
1         0.333333   0.753623  
2         0.333333   0.934783  
3         0.416667   0.311594  
4         0.583333   0.927536  
...            ...        ...  
1455      0.416667   0.920290  
1456      0.416667   0.768116  
1457      0.583333   0.500000  
1458      0.250000   0.565217  
1459      0.333333   0.673913  

[1460 rows x 8 columns]

In [51]:
for column in qual_trans.columns:
    df_scaled[column] = qual_trans[column]

In [52]:
df_scaled

GrLivArea  GarageCars  GarageArea  TotalBsmtSF  1stFlrSF  FullBath  \
0      0.259231        0.50    0.386460     0.140098  0.119780  0.666667   
1      0.174830        0.50    0.324401     0.206547  0.212942  0.666667   
2      0.273549        0.50    0.428773     0.150573  0.134465  0.666667   
3      0.260550        0.75    0.452750     0.123732  0.143873  0.333333   
4      0.351168        0.75    0.589563     0.187398  0.186095  0.666667   
...         ...         ...         ...          ...       ...       ...   
1455   0.247362        0.50    0.324401     0.155974  0.142038  0.666667   
1456   0.327619        0.50    0.352609     0.252373  0.399036  0.666667   
1457   0.377920        0.25    0.177715     0.188543  0.195961  0.666667   
1458   0.140166        0.25    0.169252     0.176432  0.170721  0.333333   
1459   0.173700        0.25    0.194640     0.205565  0.211565  0.333333   

      TotRmsAbvGrd  YearBuilt  qual_1  qual_2  qual_3  qual_4  qual_5  qual_6  \
0         0.500000   0.949275     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.333333   0.753623     0.0     0.0     0.0     0.0     0.0     1.0   
2         0.333333   0.934783     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.416667   0.311594     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.583333   0.927536     0.0     0.0     0.0     0.0     0.0     0.0   
...            ...        ...     ...     ...     ...     ...     ...     ...   
1455      0.416667   0.920290     0.0     0.0     0.0     0.0     0.0     1.0   
1456      0.416667   0.768116     0.0     0.0     0.0     0.0     0.0     1.0   
1457      0.583333   0.500000     0.0     0.0     0.0     0.0     0.0     0.0   
1458      0.250000   0.565217     0.0     0.0     0.0     0.0     1.0     0.0   
1459      0.333333   0.673913     0.0     0.0     0.0     0.0     1.0     0.0   

      qual_7  qual_8  qual_9  qual_10  
0        1.0     0.0     0.0      0.0  
1        0.0     0.0     0.0      0.0  
2        1.0     0.0     0.0      0.0  
3        1.0     0.0     0.0      0.0  
4        0.0     1.0     0.0      0.0  
...      ...     ...     ...      ...  
1455     0.0     0.0     0.0      0.0  
1456     0.0     0.0     0.0      0.0  
1457     1.0     0.0     0.0      0.0  
1458     0.0     0.0     0.0      0.0  
1459     0.0     0.0     0.0      0.0  

[1460 rows x 18 columns]

In [53]:
x_train,x_test,y_train,y_test = train_test_split(df_scaled,y, test_size = 0.25, random_state=43)

In [54]:
lr_scaled = LinearRegression()
lr_scaled.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [55]:
#Diminuir o erro em 10% é bom
#Utilizar mais features pode levar a redução 
y_pred = lr_scaled.predict(x_test)
np.sqrt(mean_squared_error(y_test,y_pred))

36789.94001804077